# Generated by Django 4.1.7 on 2023-02-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='short_url',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
