# Generated by Django 4.1.7 on 2023-02-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_token_full_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='full_url',
            field=models.URLField(),
        ),
    ]
